# user_int = int(input("Please enter an integer.\n"))
# print(user_int)
# print(type(user_int))
#
# # error_1 = int("Numb3rs 4nd $ymbols!")
# # error_2 = int("1.45")
# interesting_1 = int(11.9)
# print(interesting_1)
# # error_3 = int("10.1 + 9.3")
# interesting_2 = int(10.1 + 9.3)
# print(interesting_2)

user_float = float(input("Please enter a float.\n"))
print(user_float)
print(type(user_float))

# error_4 = float("Numb3rs 4nd $ymbols!")
interesting_3 = float("1")
print(interesting_3)
interesting_4 = float(1)
print(interesting_4)
# error_5 = float("10 + 9")
interesting_5 = float(10 + 9)
print(interesting_5)
